Repository Moong-Hackathon/backend, pull requests merged in 2025-04, with the labels that each got.

#11 feat #10: 전체 Entity 구현
  build.gradle
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Reservation.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Store.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/StoreSchedule.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/User.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/enums/DayOfWeek.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/enums/ReservationStatus.java
Labels: ✨ feature

#12 Feat #10: Entity 이름 member로 변경
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Member.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Reservation.java
Labels: 🐛 fix

#14 Feature #5 : 예약 요청한 매장 목록 전체 조회 API
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/StoreController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreReservationResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Store.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/StoreRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/StoreService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/hackathon/reservation/reservation_mvp/controller/StoreControllerTest.java
Labels: ✨ feature

#16 Feature #9 : Real-time Reservation State Event Implementation
  build.gradle
  src/main/java/com/hackathon/reservation/reservation_mvp/configuration/SecurityConfig.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/ReservationEventController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/ReservationEvent.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Reservation.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/ReservationRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/ReservationService.java
Labels: ✨ feature

#15 Feature #1 : 예약 목록 조회 API
  build.gradle
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/ApiResponse.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/BaseCode.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/BaseErrorCode.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/ErrorReasonDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/ReasonDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/status/ErrorStatus.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/status/SuccessStatus.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/exception/ExceptionAdvice.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/exception/GeneralException.java
  src/main/java/com/hackathon/reservation/reservation_mvp/configuration/SwaggerConfig.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/ReservationRestController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/converter/ReservationConverter.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/ReservationResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/ReservationRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/StoreRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationQueryService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationQueryServiceImpl.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#18 Refactor #17 : 코드 전반 리팩토링
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/ReservationSseController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/StoreOwnerReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/UserReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/StoreRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/ReservationNotificationService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/ReservationService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/StoreService.java
  src/test/java/com/hackathon/reservation/reservation_mvp/controller/ReservationSseControllerTest.java
  src/test/java/com/hackathon/reservation/reservation_mvp/controller/StoreControllerTest.java
  src/test/java/com/hackathon/reservation/reservation_mvp/controller/StoreOwnerReservationControllerTest.java
Labels: ♻️ Refactor

#19 Feature/#8: 사용자 예약 가능 매장 필터링 및 예약 생성 구현
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/UserReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreListResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreReservationRequestDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreReservationResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/MemberRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/ReservationRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/StoreService.java
Labels: 📡 API

#20 Feature #2 : 가게 예약 상태 변환 API
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/status/ErrorStatus.java
  src/main/java/com/hackathon/reservation/reservation_mvp/configuration/SecurityConfig.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/StoreOwnerReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/converter/ReservationConverter.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/ReservationResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Reservation.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/enums/ReservationStatus.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/ReservationRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationCommandService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationCommandServiceImpl.java
  src/test/java/com/hackathon/reservation/reservation_mvp/controller/ReservationSseControllerTest.java
  src/test/java/com/hackathon/reservation/reservation_mvp/controller/StoreControllerTest.java
  src/test/java/com/hackathon/reservation/reservation_mvp/controller/StoreOwnerReservationControllerTest.java
Labels: ✨ feature

#22 Release : AWS MariaDB 설정을 위한 중간 배포
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/ApiResponse.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/BaseCode.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/BaseErrorCode.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/ErrorReasonDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/ReasonDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/status/ErrorStatus.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/status/SuccessStatus.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/exception/ExceptionAdvice.java
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/exception/GeneralException.java
  src/main/java/com/hackathon/reservation/reservation_mvp/configuration/SecurityConfig.java
  src/main/java/com/hackathon/reservation/reservation_mvp/configuration/SwaggerConfig.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/ReservationSseController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/StoreOwnerReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/UserReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/converter/ReservationConverter.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/ReservationEvent.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/ReservationResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreListResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreReservationRequestDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreReservationResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Member.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Reservation.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Store.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/StoreSchedule.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/enums/DayOfWeek.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/enums/ReservationStatus.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/MemberRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/ReservationRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/StoreRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/ReservationNotificationService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/ReservationService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/StoreService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationCommandService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationCommandServiceImpl.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationQueryService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationQueryServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 📡 API

#23 Release : 배포용 application-prod.yml
  src/main/resources/application-prod.yml
Labels: 🚨 Hotfix

#24 feature #6
  src/main/java/com/hackathon/reservation/reservation_mvp/apipayload/code/status/ErrorStatus.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/ReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/StoreOwnerReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/converter/ReservationConverter.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/ReservationResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Reservation.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/ReservationRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationCommandService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationCommandServiceImpl.java
Labels: ✨ feature

#31 Feature/#30
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/StoreOwnerReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/converter/ReservationConverter.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/ReservationResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Member.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/ReservationRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationQueryService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationQueryServiceImpl.java
Labels: ✨ feature

#35 Feature #34 : 예약 상태 변경 시 SSE를 통한 실시간 알림 전송 기능 추가
  src/main/java/com/hackathon/reservation/reservation_mvp/service/ReservationNotificationService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/ReservationService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/reservation/ReservationCommandServiceImpl.java
Labels: ✨ feature

#33 Feature #32 : 사용자 예약 생성 및 가게 상세정보 조회 API 구현
  src/main/java/com/hackathon/reservation/reservation_mvp/controller/ReservationController.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/ReservationInfoDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreDetailForReservationDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreDetailResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreListResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreReservationRequestDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/dto/StoreReservationResponseDto.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Member.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Reservation.java
  src/main/java/com/hackathon/reservation/reservation_mvp/entity/Store.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/MemberRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/ReservationRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/repository/StoreRepository.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/ReservationService.java
  src/main/java/com/hackathon/reservation/reservation_mvp/service/StoreService.java
Labels: 📡 API
